RedHatInsights/tasks-frontend

src/constants.js
The Download report button should be to the left of Run task again.
=> Fix button order on completed task details

src/SmartComponents/RunTaskModal/RunTaskModal.js, src/SmartComponents/TasksPage/TasksPage.js
Cancel button should close the modal and remove any selected systems. If opening the modal from the run task again button, after selecting additional systems, and then cancelling, it should reopen with only the original pre-selected systems selected.
=> Add cancel button to run task modal

api.js, src/PresentationalComponents/DeleteCancelTaskModal/DeleteCancelTaskModal.js, src/PresentationalComponents/ExecuteTaskButton/ExecuteTaskButton.js, src/PresentationalComponents/FlexibleFlex/FlexibleFlex.js, src/SmartComponents/AvailableTasks/AvailableTasks.js, src/SmartComponents/CompletedTaskDetails/Columns.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetailsKebab/CompletedTaskDetailsKebab.js, src/SmartComponents/CompletedTasksTable/Columns.js, src/SmartComponents/CompletedTasksTable/CompletedTasksTable.js, src/SmartComponents/CompletedTasksTable/__tests__/__snapshots__/CompletedTasksTable.tests.js.snap, src/SmartComponents/CompletedTasksTable/hooks/useActionResolvers.js, src/SmartComponents/TasksPage/TasksPage.js, src/Utilities/helpers.js, src/Utilities/hooks/useTableTools/useActionResolver.js, src/Utilities/hooks/useTableTools/useTableTools.js, src/constants.js, src/store/index.js
This PR adds the ability to delete/cancel an executed (or in progress) task via Completed Tasks Table (https://marvelapp.com/prototype/6da50b0/screen/84773746) and via Complete Tasks Details (https://marvelapp.com/prototype/6da50b0/screen/84773747).
Deleting a task via the Completed Tasks Table should cause a loading state on the table and a re-render if the delete is successful. An unsuccessful delete results in toast alert.
Deleting a task via the Completed Tasks Details should cause the user to go back to the Completed Tasks Table if the delete is successful. An unsuccessful delete results in toast alert.
I have some commented out code for cancelling because it's not currently supported, but we plan to have support. I don't want to rewrite the code later, so I commented it out so I can …
=> [ADVISOR-2585] Delete executed task

src/PresentationalComponents/ExecuteTaskButton/ExecuteTaskButton.js
When no systems are selected to run a task on, the "Execute task" button is disabled.
=> Disable Execute task button when no systems selected

api.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTasksTable/__tests__/__snapshots__/CompletedTasksTable.tests.js.snap, src/Utilities/hooks/useTableTools/Components/TasksTables.js, src/Utilities/hooks/useTableTools/Components/__tests__/__snapshots__/TasksTables.tests.js.snap
Select a completed task and it should load the jobs table. The pagination is now fixed. If you don't have a task with more than 10 systems, simply run one.
=> [ADVISOR-2612] Fix jobs table pagination

src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/Filters.js
When you go to the executed task details page, you now have additional filters on the jobs table. You can now filter on the status of the job in conjunction with the system filter.
=> [ADVISOR-2652] Add status filter to jobs table

src/PresentationalComponents/ExecuteTaskButton/ExecuteTaskButton.js, src/SmartComponents/CompletedTasksTable/CompletedTasksTable.js, src/SmartComponents/RunTaskModal/RunTaskModal.js
Before, if you ran a task again from the completed tasks table, using the kebab on the right, you would be directed back to the completed tasks table after the run task again modal was closed; but the table didn't refetch the data to show you the new task being run.
To repro:
- Go to completed tasks tab (it will help if you sort the table by systems so you can find the new tasks you will soon create more easily)
- Choose a task to run again
- Click the kebab on the right column of the table
- Select "Run this task again" from the dropdown menu
- When the modal opens, select an additional system to help differntiate this task from the new one
- Click "Execute"
This PR creates a fetch after a task has been run again from the completed tasks table.
=> Fix refetch after run task again

src/SmartComponents/RunTaskModal/RunTaskModal.js, src/constants.js
This PR adds an info bar to the run task modal describing which eligible systems are being displayed.
=> [ADVISOR-2668] Add info bar to run task modal

src/SmartComponents/RunTaskModal/RunTaskModal.js, src/SmartComponents/SystemTable/SystemTable.js, src/SmartComponents/SystemTable/__tests__/SystemTable.tests.js, src/SmartComponents/SystemTable/helpers.js, src/SmartComponents/SystemTable/hooks.js
Test bulk select in the following locations:
- Available tasks -> "Run task" button
- Completed tasks -> table kebab -> "Run this task again" menu item
- Completed tasks -> select task -> "Run this task again" button in header
Note the following behavior expectations:
- Select none, select page, and select all should be the options.
- If anything is selected, clicking the bulk select checkbox should deselect all things.
- If nothing is selected, clicking the bulk select checkbox should select all things.
When testing from the "Run this task again" options, preselected systems will be passed in. Verify that making selections, then cancelling the modal, then opening it again provides the original selections. Also, test for any additional things that you think might break it.
=> [ADVISOR-2676] Add bulk select to systems table

src/SmartComponents/CompletedTaskDetails/Columns.js
To repro:
- Click "Completed Tasks" tab
- Select a completed task
The jobs table should show a column titled "Result". New mocks have that column titled "Status".
=> Change jobs table column title to "Status"

src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetailsKebab/CompletedTaskDetailsKebab.js, src/SmartComponents/CompletedTasksTable/hooks/useActionResolvers.js, src/constants.js
Before, if a task was running, you could delete it during the run. Now, we don't want to allow a deletion until the run is complete.
To test, run a task (preferrably the "Run the insights-client", and then try to delete that task via the Executed tasks table kebab and on the task details page in the top right kebab.
With this fix, it should be disabled.
=> [ADVISOR-2705] Disable delete when task is running

src/PresentationalComponents/BreadcrumbLinkItem/BreadcrumbLinkItem.js, src/SmartComponents/CompletedTaskDetails/Columns.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js
Before, if you were on `/insights/tasks/executed/{id}` and then click the "Tasks" breadcrumb link, you would be redirected to `/beta/insights/tasks/executed` instead of `/insights/tasks/executed`.
This PR properly redirects you to `beta` when you're on `beta`, and stable when you're on stable.
=> [ADVISOR-2704] Fix breadcrumb link

src/PresentationalComponents/NoResultsTable/NoResultsTable.js, src/SmartComponents/SystemTable/SystemTable.js, src/Utilities/hooks/useTableTools/Components/__tests__/__snapshots__/TasksTables.tests.js.snap
In `NoResultsTable.js` in `emptyRows `function you're hardcoding colspan: 3 which does not cause any immediate problems, but imagine you added new columns to table that's using it or used it for a larger table, then the empty state would be off center, you can either pass exact amount of columns, or simply set the colspan to 100, so you virtually never run out, we use second option in both Vulnerabilities and it works wonders.
If a table items are selectable with checkboxes, then empty state has checkbox as well. To test, go to systems table and enter a filter that causes no results. You'll see a checkbox on the empty state.
These two issues are fixed in this PR.
=> [ADVISOR-2710] Fix empty state bugs

src/SmartComponents/CompletedTasksTable/Columns.js
If you sort by Run date/time on completed task table you'll notice it sorts by month instead instead of month/day. So descending should sort - Aug 22 -> Aug 20 -> Aug 3 -> July 31 -> July 15.
The bug is that it actually sorts it like so - Aug 3 -> Aug 20 -> Aug 22 -> July 15 -> July 31. So it ends up sorting descending by month and ascending by day.
This PR fixes this issue.
=> [ADVISOR-2712] Fix Run date/time sorting

src/PresentationalComponents/RunTaskButton/RunTaskButton.js, src/PresentationalComponents/RunTaskButton/__tests__/RunTaskButton.tests.js, src/SmartComponents/TasksPage/TasksPage.js
Before, if you clicked on available task tab and click the "Run this task" button on a task, it will error out. Now, this button should open the modal and display the task information and system table.
This action should be the same for the "Run this task again" button via the completed task details page.
=> Fix run task button issue

build_deploy.sh, pr_check.sh
This adds pr_check and build_deploy scripts for containerizing tasks-frontend. Currently, these scripts do not get auto-triggered until containerization is finished.
Reference: https://consoledot.pages.redhat.com/docs/dev/getting-started/frontend-migration.html#_quay_repo
=> add pr_check and build_deploy scripts

package-lock.json, package.json, src/PresentationalComponents/WithPermission/WithPermission.js, src/PresentationalComponents/WithPermission/__tests__/WithPermission.tests.js, src/PresentationalComponents/WithPermission/__tests__/__snapshots__/WithPermission.tests.js.snap, src/Routes.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/__tests__/CompletedTaskDetails.tests.js
This PR adds RBAC security to the frontend. At this point, we only have `tasks:*:*`, `inventory:*:*` and `inventory:*:read`. I block access to every route of the app if a user doesn't have `tasks:*:*` and I only block the SystemsTable when a user doesn't have `inventory:*:*` OR `inventory:*:read`.
If you don't have experience setting up RBAC permissions, I can help with showing you how to do it in order to properly test this. You can surely just set `hasAccess` manually in the code, but that doesn't quite have the same effect as setting RBAC perms. Let me know if you need guidance.
=> [ADVISOR-2723] Add RBAC

src/SmartComponents/CompletedTaskDetails/Columns.js
This PR adds canned messages for a job when it has failed or timed out. To test, find a completed task with a job that has a status of 'Failure' or 'Timeout'.
=> [ADVISOR-2793] Add messages for fail and timeout

build_deploy.sh, deploy/frontend.yml, pr_check.sh
follow up work for containerization. 
- adds `frontend.yaml` for navigation in ephemeral environments
- makes build_deploy and pr_check files executable
=> adds deploy frontend.yaml file, makes pr_check and build_deploy scripts executable

deploy/frontend.yml
QE found an error with the deploy script and I think it is just a spacing issue.
```
raise ParserError("while parsing a block collection", self.marks[-1],
yaml.parser.ParserError: while parsing a block collection
in "<byte string>", line 22, column 9:
- expandable: true
^
expected <block end>, but found '?'
in "<byte string>", line 23, column 9:
title: Toolkit
^
ERROR: deploy failed: while parsing a block collection
in "<byte string>", line 22, column 9:
- expandable: true
^
expected <block end>, but found '?'
in "<byte string>", line 23, column 9:
title: Toolkit
^
```
=> Fix error in deploy script

deploy/frontend.yml
This fixes the URL  for the quay repo to be able to deploy the tasks-frontend container into the Ephemeral Environment. The URL should point to the  page where list of image tags are listed, not to a landing repo page.
=> fix(RHCLOUD-20293): updates the url for quay repo

src/SmartComponents/CompletedTaskDetails/Filters.js
Find a completed task and view the status filter for the jobs table. The dropdown should no longer include "Cancelled" in the list.
=> [ADVISOR-2851] Remove "Cancelled" from jobs filter

src/PresentationalComponents/SplitMessages/SplitMessages.js, src/SmartComponents/CompletedTaskDetails/Columns.js
There were scenarios where a Successful job would complete with no alert, but did contain a message. The logic I was using wasn't showing those types of messages. Now this PR does show those messages.
Let me know if you want help on choosing the completed tasks that will get the information you need to review this PR.
=> [ADVISOR-2855] Rework job message logic

src/SmartComponents/CompletedTaskDetails/Columns.js, src/SmartComponents/CompletedTaskDetails/Filters.js
If a system has been deleted from inventory and that system is part of a completed task run, the "System name" column will no longer be blank, but will include gray text reading "System deleted".
=> [ADVISOR-2857] Add canned name for deleted system

src/PresentationalComponents/TasksTabs/__tests__/TasksTabs.tests.js, src/PresentationalComponents/TasksTabs/__tests__/__snapshots__/TasksTabs.tests.js.snap, src/SmartComponents/CompletedTasksTable/CompletedTasksTable.js, src/SmartComponents/CompletedTasksTable/Filters.js, src/SmartComponents/CompletedTasksTable/__tests__/__snapshots__/CompletedTasksTable.tests.js.snap, src/SmartComponents/TasksPage/__tests__/TasksPage.tests.js, src/SmartComponents/TasksPage/__tests__/__snapshots__/TasksPage.tests.js.snap, src/constants.js
Tabs have been renamed from 'Available tasks' and 'Completed tasks' to 'Available' and 'Activity'.
We have also added a status filter to the activity table. In a later PR I will rename all instance of Completed tasks to Activites.
=> Update tabs and add status filter

src/SmartComponents/completedTaskDetailsHelpers.js
To repro:
- Find a completed task with a deleted system
- Click the Run task again button in the top right
- Click the Execute task button
Notice when you load the systems table, the count in the bulk select includes the deleted system, but the actual number of selected items is lower than that number.
When you click to execute the task, you will get an error because you submitted an id that no longer exists.
This PR fixes both of these issues.
=> [ADVISOR-2864] Fix deleted system in Run task again

src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/completedTaskDetailsHelpers.js
Before, if a job completed successfully but had 0 inibitors out of n potential problems, the expandable row showing the problems for that job would not populate. This PR fixes that.
=> Show job details with success and 0 inhibitors

src/SmartComponents/SystemTable/SystemTable.js, src/store/index.js
To repro:
- Navigate to "Activity" tab
- refresh page
- click a kebab on a task and click "Run this task again"
The modal should open and then close. If you try again, the page will error out.
You can get the inventory table to load if you open the run task modal from the "Available" tab first, and then open via "Run this task again"
=> Fix system table load error

src/SmartComponents/TasksPage/TasksPage.js, src/SmartComponents/TasksPage/__tests__/TasksPage.tests.js
Back button was broken in 2 instances.
First:
- Load app
- Click Activity tab
- Click back button url updates, but doesn't go back.
Second:
- Load app
- Click Activty tab
- Click back to Available tab
- Click "Run task" button
- Click back button url updates, but doesn't go back
Now, the back button goes back properly. There is still an issue with the back button in relation to global filters, but that will be fixed in a future PR.
=> [ADVISOR-2884] Back button works properly

src/SmartComponents/CompletedTaskDetails/__tests__/CompletedTaskDetails.tests.js, src/helpers.js
There was only one instance of using insights.chrome. That has been updated.
=> [RHIF-130] adopt useChrome hook

src/SmartComponents/ActivityTable/ActivityTable.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js
ActivityTable and CompletedTaskDetails were failing because of async calls. This PR fixes those issues and those pages should work fine now.
=> fix(ADVISOR-3118): remove async in useEffect calls

package-lock.json, package.json, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/ExpandedIssues.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/JobResultsDetails.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/jobResultsDetailsHelpers.js, src/SmartComponents/CompletedTaskDetails/__tests__/__fixtures__/completedTasksDetails.fixtures.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap, src/SmartComponents/completedTaskDetailsHelpers.js
Currently, we have only one task that displays job results in the expanded row. That content is unique to the specific task and we need to make a failsafe so that if a job is run that doesn't have a `report_json` that it will fallback to the `report` property and display the text.
To test, go to this line: https://github.com/RedHatInsights/tasks-frontend/blob/master/src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js#L76 and replace it with https://github.com/RedHatInsights/tasks-frontend/blob/master/src/SmartComponents/CompletedTaskDetails/__tests__/__fixtures__/completedTasksDetails.fixtures.js#L62.
This will use the fixture to display the scenario we're testing. In the instance where `report_json` is not provided, we'll rely on the backend to provide text in the `report` …
=> [ADVISOR-3090] Display text when no report_json

src/Routes.js
[Ticket](https://issues.redhat.com/browse/RHIF-200)
Just a small fix so this is consistent between apps
If the request fails, user will still see the empty state like in other apps
=> fix(RHIF-200): Show empty state by default

src/SmartComponents/AvailableTasks/AvailableTasksTable.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/EntryDetails.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/EntryRow.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/JobResultsDetails.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/jobResultsDetailsHelpers.js, src/SmartComponents/CompletedTaskDetails/TaskEntries.js, src/SmartComponents/CompletedTaskDetails/__tests__/__fixtures__/completedTasksDetails.fixtures.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap, src/SmartComponents/completedTaskDetailsHelpers.js
This PR mainly makes some components more generic so different types of tasks can display on the same component. We've done this by creating constants that define how each unique task defines its statuses and other data, and then we map the executed task to the constant via the task_slug and pull in the constant.
=> feat(HMS-1925):Add Centos preconversion support

src/SmartComponents/AvailableTasks/AvailableTasksTable.js
With this PR, we are temporarily hiding the new preconversion task in the Available Tasks tab when in stage-stable and prod-stable. It should still be visible in preview environments.
=> temporarily hide preconversion in stable envs

src/SmartComponents/ActivityTable/ActivityTable.js, src/SmartComponents/ActivityTable/Columns.js, src/SmartComponents/ActivityTable/__tests__/__snapshots__/ActivityTable.tests.js.snap, src/Utilities/hooks/useTableTools/__tests__/__fixtures__/columns.fixtures.js, src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useRowsBuilder.tests.js.snap, src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useTableSort.test.js.snap, src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useTableTools.tests.js.snap
This PR updates the "Run date/time" column on the Activity table to display the start_time instead of the end_time. This also removes the "Running" status from the same column. Now, we'll only look to the status column for statuses.
=> fix: update run date/time column

package-lock.json, package.json, src/SmartComponents/AvailableTasks/AvailableTasksTable.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap, src/SmartComponents/RunTaskModal/RunTaskModal.js
preconversion tasks (only viewable in stage-beta at the time of pushing this PR), have links that are activated via markdown. Currently they don't work, but this PR adds markdown.
You should see these links in 3 places for preconversion tasks:
- available tasks
- run task modal (click the `Run task` button)
- completed task details (go to Activity table and open a preconversion task
=> fix(HMS-2709): add markdown conversion

src/SmartComponents/CompletedTaskDetails/JobResultsDetails/EntryDetails.js
When a pre-upgrade analysis task has a job that doesn't return a remediation, then it leaves the field off completely. We currently handle that correctly. But the new pre-conversion analysis tasks have jobs that, when a remediation isn't provided, still provides the remediation key value pair, but it is empty. This is why the commit checks for `detail?.remediations[0]?.context !== ''`. Pre-conversion tasks return:
```
detail: {
remediations: [
context: '',
],
},
```
Whereas pre-upgrade tasks return the following when no `detail.remediations` when there is no remediation.
This PR handles both scenarios. Let me know if you need ids to test both types of tasks.
=> fix(HMS-2644): catch new remediation field structure

src/PresentationalComponents/ExecuteTaskButton/ExecuteTaskButton.js, src/PresentationalComponents/ExecuteTaskButton/__tests__/ExecuteTaskButton.tests.js, src/SmartComponents/ActivityTable/Columns.js, src/SmartComponents/ActivityTable/__tests__/ActivityTable.tests.js, src/SmartComponents/ActivityTable/__tests__/__snapshots__/ActivityTable.tests.js.snap, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/__tests__/__fixtures__/completedTasksDetails.fixtures.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap, src/SmartComponents/RunTaskModal/RunTaskModal.js, src/Utilities/hooks/useTableTools/Components/__tests__/TasksTable.fixtures.js, src/Utilities/hooks/useTableTools/Components/__tests__/__snapshots__/TasksTables.tests.js.snap, src/constants.js
This PR adds the ability to give your tasks a unique name. You can name tasks the same as another task. If an error occurs in the creation of the executed task, the run task modal will stay open and an error will be displayed.
To test, open an available task and notice that the task_slug populates in the text input box. You can change the name of the task to whatever you want, select your systems, and run the task. The notification should allow you to navigate to the new task.
You should also see the new task name populated in the Activity table as well as the executed task details. And, if you select Run task again, you should see the modal populate with the same task name.
=> feat(RHINENG-1454): Add ability to name tasks

src/PresentationalComponents/ExecuteTaskButton/ExecuteTaskButton.js, src/SmartComponents/ActivityTable/ActivityTable.js, src/SmartComponents/ActivityTable/__tests__/ActivityTable.tests.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap, src/SmartComponents/RunTaskModal/RunTaskModal.js, src/constants.js
- When viewing the Task Details in the Activity Tab, then I will see the name given to the task in the task details and I see the default task name below it
- In Run Task MOdal, disable the Execute task button when the task name field is empty
- also:
click Run task
enter empty name
cancel modal
click Run task
The Task name stays empty, but this PR fixes that.
=> fix(RHINENG-1454): handle bugs

src/SmartComponents/SystemTable/helpers.js
Currently in stage-beta, if you add os filters, the system fetch will break because it's not properly adding the versions to the request string. This PR properly creates the fetch request.
It will only work in stage-beta at this point. It is currently not fetching correctly because the backend needs a change. if you filter by centos version 7.9 and rhel version 8.8, it will try to fetch centos versions 7.9 and 8.8 and rhel versions 7.9 and 8.8.
=> fix: properly filter by os version

src/SmartComponents/SystemTable/SystemTable.js
With this PR, CentOS Linux versions should show up in the os filter dropdown on the inventory table. Go to Available tasks tab and click Run task on one of the available tasks. The systems table will populate there. In stage-preview, you shouldn't see the CentOS Linux versions, but this PR exposes them.
=> fix(RHINENG-2529): show centos versions in os filter

src/SmartComponents/RunTaskModal/RunTaskModal.js, src/SmartComponents/SystemTable/SystemTable.js, src/SmartComponents/SystemTable/hooks.js
When you're selecting systems to run a task on, if you filter the systems and then try to select all, it doesn't properly select all of the filtered systems. It selects the correct amount, but only based on a fetch of all systems and not the filtered systems.
=> fix(RHINENG-2490): bulk select all filtered systems

src/SmartComponents/CompletedTaskDetails/TaskEntries.js
There is a new task called leapp-upgrade that is like leapp-preupgrade. Certain leapp-upgrades task details will currently fail because there isn't a dictionary to map the severities to the visual items in the jobs table. This PR adds a dictionary.
I'm not sure if I can run this task on a system yet in order to return data I would need to test that this fix works. I'm hoping to push this to prod where I know an existing task fails and test it there. This PR won't break prod if it gets pushed up and doesn't fix the issue.
=> fix(RHINENG-2644): Add dictionary for leapp-upgrade

src/SmartComponents/SystemTable/helpers.js
The current os request to tasks/system api sends the os name and version separately. When a centos and rhel version are added to the request, it fetches the versions for both os names. So if you request `os_name=RHEL&os_version=7.9&os_name=CentOS Linux&os_version=8.3`, you will systems that match RHEL 7.9, RHEL 8.3, CentOS Linux 7.9, and CentOS Linux 8.3.
A new MR on the backend updates the request so you request the os name and version together; like, `&operating_system=RHEL|7.9&operating_system=CentOS Linux|8.3`.
=> fix(RHINENG-2581): update os filter request to api

src/App.scss, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/EntryDetails.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
We were incorrectly checking the `detail.diagnosis` value as an object when it was, in fact, an array. This PR combines some code for simplicity and properly checks the value and displays it.
To test, in insights account, check `executed_task/5330`. You should be able to expand some of the job details and see that the `diagnosis` field doesn't populate in the details. When running this PR, you should see it.
Please also check that `executed_task/5331` also works correctly by continuing to show `remediations` field.
=> fix(RHELC-1186): diagnosis doesn't show for pre-conversion

src/SmartComponents/RunTaskModal/RunTaskModal.js, src/SmartComponents/warningConstants.js
For pre-conversions, we need to include a warning message about backing up systems. I've made this flexible so different tasks can have different alerts. I suspect conversions will need a similar warning.
To test, go to tasks in stage-preview, go to `Available` tab and click the Run task button for multiple tasks. You should only see the warning alert for pre-conversion task. You should also test this functionality by going to the `Activity` tab, and clicking the kebab, and `Run this task again` on multiple tasks. Also when you open specific tasks from the Activity table, there is a `Run this task again` button in the top right. This functionality should also be here.
=> chore(HMS-2110): Add alert to backup for pre-conversions

src/SmartComponents/CompletedTaskDetails/Columns.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js
We need to hide the status column for convert to rhel tasks until we nail down a redesign for the column. It's currently confusing with the "Success" status when there are inhibitors.
To test:
1. Go to Activity tab and find a `Convert2RHEL Conversion(Stage)` task
2. Click it
3. See that the status column is not visible, and that you can't filter on status
4. Go to Activity tab and find any other task
5. Click it
6. See that the status column is visible, and that you CAN filter on status.
=> chore(HMS-3012): Temporarily hide column

src/SmartComponents/AvailableTasks/AvailableTasksTable.js
On Nov 14 we are exposing preconversion analysis in prod-stable and conversions in prod-preview. The conversion task will be active in prod and so this PR no longer hides preconversions in stable and when conversions is active, it will hide it in stable.
=> chore(RHINENG-2873): Show preconversion and hide conversions

src/PresentationalComponents/ExecuteTaskButton/ExecuteTaskButton.js, src/SmartComponents/ActivityTable/ActivityTable.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/RunTaskModal/InputParameters.js, src/SmartComponents/RunTaskModal/RunTaskModal.js, src/SmartComponents/RunTaskModal/RunTaskModalBody.js, src/SmartComponents/RunTaskModal/SystemsSelect.js, src/SmartComponents/RunTaskModal/__tests__/InputParameters.tests.js, src/SmartComponents/RunTaskModal/__tests__/RunTaskModal.fixtures.js, src/SmartComponents/RunTaskModal/__tests__/RunTaskModal.tests.js, src/SmartComponents/RunTaskModal/__tests__/RunTaskModalBody.tests.js, src/SmartComponents/RunTaskModal/__tests__/__fixtures__/RunTaskModal.fixtures.js, src/SmartComponents/RunTaskModal/__tests__/__snapshots__/RunTaskModal.tests.js.snap, src/SmartComponents/RunTaskModal/hooks/useBulkSystemSelect.js, src/SmartComponents/RunTaskModal/hooks/useModalActions.js, src/SmartComponents/TasksPage/TasksPage.js, src/constants.js
Some tasks will request certain parameters in order to complete the task. Those parameters may or may not be required, but they will be a part of the response when you fetch task details.
When a task doesn't have parameters, you can execute the task after selecting systems. If a task does have parameters, you can click the "Next" button after selecting a system.
Clicking next button will bring up the input page for parameters. As long as all required parameters are filled in, then you can execute the task.
Required parameters are validated by the form input. On first load of the page, the validation error text will not show on an empty input. But if you type something and delete it, then you'll see the validation error appear. Either way, the Execute button should not be enable unless all …
=> feat(RHIN-1101): Add Input Parameters to Tasks

src/Utilities/hooks/useTableTools/__tests__/useRowsBuilder.tests.js, src/Utilities/hooks/useTableTools/useRowsBuilder.js, src/Utilities/hooks/useTableTools/useTableTools.js
**Description of Problem**
There's a small bug in Tasks on the Activity table. When you're on any page other than 1 and you delete an activity, the table shows a No results empty state instead of loading rows.
**How reproducible**
Always
**Steps to Reproduce**
- Go to Tasks
- Click Activity Tab
- Go to page 2+
- Delete an activity via the kebab
**Actual Behavior**
Table shows a "No results" empty state.
**Expected Behavior**
Should show loading rows
**Additional info**
This happens because the table component receives an array of 5 loading row components. Then it tries to paginate that data, and the `page` is currently set to a page over page 1, so if you're looking at 10 per page and you're on page 2, the 5 items sent in get paginated out.
This fix will skip pagination if the table is in …
=> fix(RHINENG-3105): loading rows not showing on activity delete

src/SmartComponents/warningConstants.js
[HMS-3082](https://issues.redhat.com/browse/HMS-3082)
Slug for task in preview is `convert-to-rhel-conversion` so this should work similarly to preanalysis alert.
=> Add c2r conversion task backup alert

src/SmartComponents/CompletedTaskDetails/TaskEntries.js, src/SmartComponents/CompletedTaskDetails/__tests__/CompletedTaskDetails.tests.js, src/SmartComponents/CompletedTaskDetails/__tests__/__fixtures__/completedTasksDetails.fixtures.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
This PR attempts to display overridable results in convert2rhel tasks as inhibitors. To test, login to insights account and go to `/tasks/executed/6354`. The first entry should be displayed as an inhibitor if you expand the row. If you check the `jobs` network request, you'll see that the entry is actually set to 'OVERRIDABLE' severity.
The script will be updated later for overriable tasks and we'll simply convert the `TaskEntries` back and update tests.
=> fix(HMS-3139) Temporarily display overridable as inhibitor

src/SmartComponents/AvailableTasks/AvailableTasksTable.js
To test:
1. update dev.webpack.config to `env: 'prod-stable'`
2. go to prod.foo.redhat.com:1337/insights/tasks
You should see the 'Convert to RHEL from CentOS Linux 7' task in the table on the Available tab.
If you look in console.redhat.com, you will not see that task. This PR is to expose the task in production.
=> Show Convert2RHEL task in production

src/SmartComponents/RunTaskModal/InputParameters.js
To test:
- Go to tasks
- On available tab, select Test Task with Parameters
- Select a random system
- In the `path` field, start typing spaces with the spacebar
This should render the `Execute Task` button as disabled until characters are added.
=> bug(RHIN-1128): Disable execution with whitespace

deploy/testing-integration.yml
Adding a new job template that will run end-to-end tests after deployment.
(A new saas file deployment will need to be added to app-interface for this template to take effect.)
=> chore(HMS-2515): Add post-deploy e2e test template

src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/ParameterDetails.js
This is a companion PR to this PR: https://github.com/RedHatInsights/tasks-frontend/pull/126
If you follow the guide to run a task with parameters, then you can use this PR to check that the parameters are shown in the completed task details page. Otherwise, you can simply find a completed task that already exists and use that.
To test:
- Go to `/insights/tasks`
- Click the 'Activity' tab
- In the search bar, type 'parameter'. This should show some existing tasks that have run with parameters
- Click the task to open the completed task details page
- Check under the description of the task to see the 'Parameter details' section
Do this same thing with a non-parameter task and make sure that 'Parameter details' do NOT appear.
=> feat(RHINENG-6101): Add parameter details to CompletedTaskDetails

src/SmartComponents/ActivityTable/Filters.js
The user can create their own name for a task rather than use the default task_title field.  This PR modifies the Task name filter to also consider the name field as well as the task_title field when filtering the text.
=> fix(RHINENG-7678): Include task name in Task name filter

src/SmartComponents/ActivityTable/Filters.js
Ooops.  I missed testing this in my last commit.
Before fix:
After fix:
=> fix(RHINENG-7678): Task name filters on task name only

src/SmartComponents/SystemTable/helpers.js
- Allows sorting by both name and version together
Before PR, sorting is done using OS version only, so CentOS and RHEL hosts are intermixed:
After PR, the sorting is done using both OS name and version (via the new Tasks API sort parameter 'os'):
=> fix(RHINENG-7680): Sort system OS column with new API 'os' sort param

src/SmartComponents/CompletedTaskDetails/TaskEntries.js, src/SmartComponents/CompletedTaskDetails/__tests__/__fixtures__/completedTasksDetails.fixtures.js
`leapp-preupgrade` prod task newly has stage version `leapp-preupgrade-stage` for testing of new leapp reporting schema. I don't expect any problems with other parsing.
Just for reference: [old one](https://github.com/oamg/leapp/blob/master/report-schema-v110.json) vs [new one](https://github.com/oamg/leapp/blob/master/report-schema-v120.json), only significant change is consolidating `"flags"` and `"tags"` entry properties to `"groups"`.
=> fix: Add severity map for leapp-preupgrade-stage slug

api.js, src/SmartComponents/AvailableTasks/AvailableTasks.js
Before PR - only 10 available tasks listed:
After PR - all available tasks listed (11):
=> fix(RHINENG-8085): Workaround for only 10 available tasks listed

src/SmartComponents/CompletedTaskDetails/TaskEntries.js
Related to OAMG-10608 and OAMG-10609
Goal of this change is to extend severity maps so we can adjust tasks to distinguish high risk issues and inhibitors, e.g. image below shows that system has one inhibitor, but all red records have high severity in report which makes UI look same. (this is caused by leapp report structure and tasks will be changed to use new inhibitor severity - the changes can be seen [in this upstream PR](https://github.com/oamg/leapp-insights-tasks/pull/12))
=> feat: distinguish leapp inhibitors from other high risk issues by extending severity mapping

src/PresentationalComponents/TasksPopover/TasksPageHeaderPopover.js, src/constants.js
The popover links are broken (again).  This PR fixes the links (again).  It opens the documentation in a new browser tab/window which I think is a better user experience than opening them in the same tab/window.
=> Fix documentation link 404s in About Tasks popover

src/SmartComponents/RunTaskModal/hooks/useBulkSystemSelect.js, src/SmartComponents/SystemTable/SystemTable.js, src/SmartComponents/SystemTable/constants.js, src/SmartComponents/SystemTable/helpers.js, src/SmartComponents/SystemTable/hooks.js, src/helpers.js
Eligible systems are selectable:
Not eligible systems have a tooltip and aren't selectable:
=> feat(RHINENG-2324): Add Eligibility filter & column to SystemTable

src/SmartComponents/SystemTable/SystemTable.js, src/SmartComponents/SystemTable/constants.js, src/SmartComponents/SystemTable/helpers.js
After the PR the group column is visible and sortable and displays hosts without groups in the standard format:
Also the group filtering works as expected:
=> feat(RHINENG-8320): Add groups column & filter to SystemTable

src/SmartComponents/RunTaskModal/hooks/useBulkSystemSelect.js, src/SmartComponents/SystemTable/SystemTable.js
The Tasks API paginator responds with a maximum of 1000 systems, even if the account has more  than 1000 systems and the request params contain something like '/systems?limit=20000&offset=0'.  The BulkSelect all component needs to retrieve systems in batches of 1000 so all systems can be selected, not just the systems in the first 1000.
Before the PR only systems within the first 1000 may be selected in the bulkSelect, so there are only 5 matching systems:
After the PR all 3125 systems may be selected within the bulkSelect, so there are 12 matching systems which is the correct number:
=> fix(RHINENG-8404): Bulk select all systems in batches in SystemTable

api.js, config/dev.webpack.config.js, package-lock.json, package.json, src/App.scss, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/JobLogDrawer.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/JobResultsDetails.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/LogDrawerDetails.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/__tests__/JobLogDrawer.tests.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/__tests__/LogDrawerDetails.test.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap, src/constants.js
When a task has completed, that task may have a job or series of jobs that have logs. This PR adds the ability for a user to view these logs in the UI.
A "View logs" link should appear when a job (system) is expanded and that job has logs. When the link is clicked, a drawer with a log viewer component is displayed. That log viewer has the ability to search, export as a file, and open the log in a new tab.
For now, we are adding the "View log" link in the expanded details of the job. In the next iteration, we will be adding the "View logs" action to a kebab in the table next to the job. For now, let's test the link.
Finding a task with logs may be difficult, but if you run this on prod.foo and sign into the insights-qa account, you can go to `/insights/tasks/executed/10753` and view a task …
=> feat(RHINENG-2263): Add log viewer to task details

src/SmartComponents/RunTaskModal/SystemsSelect.js
Fixes https://issues.redhat.com/browse/RHINENG-7780.
This adds an extra title to all tasks alerts that notify about the systems eligible for a specific task according to mocks.
=> fix(RHINENG-7780): Change alert title and text in SystemsSelect

src/SmartComponents/AvailableTasks/AvailableTasksTable.js, src/SmartComponents/AvailableTasks/TaskCard.js, src/SmartComponents/AvailableTasks/__tests__/AvailableTasks.tests.js, src/SmartComponents/AvailableTasks/__tests__/AvailableTasksTable.tests.js, src/SmartComponents/AvailableTasks/__tests__/TaskCard.test.js
Implements https://issues.redhat.com/browse/RHINENG-8308.
This makes the task cards on the main page expandable hiding description and playbook download link by default. This also slightly improves the tests for the related components.
Go to the available tasks list and make sure the cards are expandable.
=> feat(RHINENG-8308): Make task cards expandable

src/PresentationalComponents/ExecuteTaskButton/ExecuteTaskButton.js, src/PresentationalComponents/ExecuteTaskButton/__tests__/__snapshots__/ExecuteTaskButton.tests.js.snap, src/PresentationalComponents/RunTaskButton/RunTaskButton.js, src/PresentationalComponents/RunTaskButton/__tests__/__snapshots__/RunTaskButton.tests.js.snap
Fixes https://issues.redhat.com/browse/RHINENG-8314.
A quick PR to slightly rename the button names. On the tasks list page, "Run tasks" -> "Select systems", in the select systems modal, "Execute task" -> "Run task".
=> fix(RHINENG-8314): Rename action buttons

src/PresentationalComponents/DeleteCancelTaskModal/DeleteCancelTaskModal.js, src/SmartComponents/RunTaskModal/RunTaskModal.js
Fixes https://issues.redhat.com/browse/RHINENG-8309.
Open any quickstart, go to Tasks and try to click on "Select systems" for any task. The modal must not cover the quickstarts section. Repeat the same for delete/cancel task modal.
=> fix(RHINENG-8309): Don't cover quickstarts when modal open

src/PresentationalComponents/EmptyStateDisplay/EmptyStateDisplay.js, src/SmartComponents/AvailableTasks/QuickstartButton.js, src/SmartComponents/SystemTable/NoCentOsEmptyState.js, src/SmartComponents/SystemTable/SystemTable.js, src/SmartComponents/SystemTable/__tests__/SystemTable.tests.js
Implements https://issues.redhat.com/browse/RHINENG-8945.
This adds special empty state for conversion and pre-conversion tasks explicitly telling that there are no CentOS systems registered in account. Other tasks must not be affected.
The primary button must open a quickstart content. If the content (= feature flag for this quickstart is off) is not available, the button is hidden. The secondary link opens a documentation page.
Log into account without any CentOS systems registered. Navigate to conversion or pre-conversion task. Make sure you see the updated empty state.
=> feat(RHINENG-8945): Add new empty state for conversion tasks

src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/constants.js
Before this PR, if a task has no jobs (which shouldn't occur, but does occasionally) the tasks table appears to continually load forever:
After the PR, an empty state banner is displayed:
=> fix(RHINENG-9145): Display empty state banner if task has no jobs

src/SmartComponents/AvailableTasks/QuickstartButton.js
No jira.
This sets the correct names for the pre-conversion, conversion and leapp (8to9) quickstarts (referenced in https://github.com/RedHatInsights/quickstarts/tree/main/docs/quickstarts).
Go to /tasks/available in stage, find any available tasks that have quickstarts enabled and click "Help me get started"; you should see a quickstart displayed. The conversion QS content PR is not yet merged (https://github.com/RedHatInsights/quickstarts/pull/185), so this most probably won't work which is expected.
=> chore: Align conversion QS names

src/SmartComponents/RunTaskModal/RunTaskModal.js, src/SmartComponents/RunTaskModal/SystemsSelect.js, src/SmartComponents/RunTaskModal/__tests__/RunTaskModal.tests.js, src/SmartComponents/RunTaskModal/hooks/useModalActions.js
Fixes https://issues.redhat.com/browse/RHINENG-3779.
This ensures users cannot run a task with an empty task name field.
Go to /tasks/available, open any task. Empty the task name field or put any number of whitespace characters. The field should indicate invalid input and disable "Run task" button.
=> fix(RHINENG-3779): Prevent empty custom task name

src/SmartComponents/RunTaskModal/RunTaskModalBody.js, src/SmartComponents/RunTaskModal/SystemsSelect.js, src/SmartComponents/RunTaskModal/TaskDescription.js, src/SmartComponents/RunTaskModal/TaskName.js, src/SmartComponents/RunTaskModal/__tests__/TaskDescription.test.js, src/SmartComponents/RunTaskModal/__tests__/TaskName.test.js
No jira.
This aims to split SystemsSelect component into smaller components (TaskName, TaskDescription), that would have their own separated state and business logic.
The modal should work as before the PR. The tests must pass.
=> refactor: Refactor RunTaskModal children components

src/SmartComponents/CompletedTaskDetails/TaskEntries.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
Fixes https://issues.redhat.com/browse/RHINENG-10046.
Reverts https://github.com/RedHatInsights/tasks-frontend/commit/ccc7419249ca430a96a7c98f17ba7f10c411d7cb.
When we allow users' input in Tasks, it will be possible for a customer to override an inhibitor detected in a pre-conversion analysis report directly in the Insights UI. The goal of this ticket is to let customers visually know that an overridable inhibitor has been detected, and to document how to override it.
An "overridable" label is shown instead of the current "inhibitor" label when a detected conversion inhibitor is overridable
The "overridable" label was originally being displayed but it was replaced with "inhibitor" under [HMS-3139](https://issues.redhat.com/browse/HMS-3139) when we realized it's not possible to override …
=> fix(RHINENG-10046): Rename Inhibitor back to Overridable

src/SmartComponents/ActivityTable/__tests__/ActivityTable.tests.js, src/SmartComponents/CompletedTaskDetails/Columns.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/__tests__/CompletedTaskDetails.tests.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap, src/Utilities/__tests__/__snapshots__/helpers.tests.js.snap, src/Utilities/hooks/useTableTools/__tests__/__fixtures__/columns.fixtures.js, src/Utilities/hooks/useTableTools/__tests__/__fixtures__/items.fixtures.js, src/Utilities/hooks/useTableTools/__tests__/__fixtures__/jobResultsItems.fixtures.js, src/Utilities/hooks/useTableTools/__tests__/__snapshots__/reportParser.test.js.snap, src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useExport.test.js.snap, src/Utilities/hooks/useTableTools/__tests__/__snapshots__/usePaginate.test.js.snap, src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useRowsBuilder.tests.js.snap, src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useTableSort.test.js.snap, src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useTableTools.tests.js.snap, src/Utilities/hooks/useTableTools/__tests__/reportParser.test.js, src/Utilities/hooks/useTableTools/__tests__/useExport.test.js, src/Utilities/hooks/useTableTools/__tests__/usePaginate.test.js, src/Utilities/hooks/useTableTools/__tests__/useRowsBuilder.tests.js, src/Utilities/hooks/useTableTools/__tests__/useTableSort.test.js, src/Utilities/hooks/useTableTools/__tests__/useTableTools.tests.js, src/Utilities/hooks/useTableTools/reportParser.js, src/Utilities/hooks/useTableTools/useExport.js, src/Utilities/hooks/useTableTools/useExportHelpers.js
Implements https://issues.redhat.com/browse/RHINENG-3781.
This improves the CSV and JSON export of the completed task report. In addition to System name, Status, Message columns, it now also includes further information about the executed job (from `report`, `report_json` fields).
- The `useExport` hook now supports `prepareItems` that allows to pre-process the items from the table before the CSV report is generated and `extraExportColumns` that extend the visible columns with the columns that will be added in the final CSV/JSON export.
Go to /tasks/executed and find any executed job. Try to find the results with some findings (warnings, errors, info messages) or just with some plain report. Export the table as CSV/JSON structure and verify it's correct and up to the information present …
=> feat(RHINENG-3781): Include report and report_json in the extended CSV/JSON report

src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/JobLogDrawer.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
The JobLogDrawer has been moved out of the Page component and wrapped around the contents of the CompletedTaskDetails component.
Previously, we had to put the Drawer inside of the Page component in order to display the drawer correct when expanded. But this caused there to be an additional scrollbar on the page.
Steps to Reproduce
- Find a tasks execution with more than 20 hosts or execute one
- Click on the task details to see individual host results
- Select the paginator to show more than 10 (or simply shrink the height of the page)
- Try to scroll the list
Also, test the JobLogDrawer by clicking the kebab on a system and click "View system logs" and make sure the functionality has remained.
=> fix(RHINENG-10944): Move Drawer out of Page component

src/SmartComponents/RunTaskModal/ConversionTaskInputParameters.js, src/SmartComponents/RunTaskModal/ParameterCheckbox.js, src/SmartComponents/RunTaskModal/ParameterCheckboxGroup.js, src/Utilities/helpers.js, src/constants.js, src/helpers.js
Screenshots showing the Parameter form with the optional repositories checkboxes all checked and the value produced that is sent to the Tasks API:
More screenshots showing none of the optional repositories checkboxes checked and the value 'None' sent to the backend:
=> feat(RHINENG-11806): Handle OPTIONAL_REPOSITORIES task parameter

src/SmartComponents/SystemTable/constants.js, src/helpers.js
- Makes it more obvious there is a hoverable popover and easier to read the contents
Before PR, the tooltip isn't obvious and its hard to read:
After PR, the popover is more obvious and easy to read the reasons why the system is not eligible:
=> fix(RHINENG-12204): Change Not eligible systems tooltip into popover

src/SmartComponents/RunTaskModal/ConversionTaskInputParameters.js, src/SmartComponents/RunTaskModal/InputParameters.js, src/SmartComponents/RunTaskModal/ParameterCheckbox.js, src/SmartComponents/RunTaskModal/ParameterDropdown.js, src/SmartComponents/RunTaskModal/ParameterMultiSelect.js, src/SmartComponents/RunTaskModal/helpers.js, src/Utilities/helpers.js
If a parameter has multi_valued=true set, then the FE will display a dropdown in which multiple values can be selected:
Selected values will be sent to the backend joined by commas:
=> feat(RHINENG-10663): Add multiselect dropdown for multi_valued parameters

src/SmartComponents/RunTaskModal/RunTaskModalBody.js, src/SmartComponents/RunTaskModal/SystemsSelect.js, src/SmartComponents/SystemTable/SystemTable.js
Alert box only displayed when Eligible Systems filter is active:
=> fix(RHINENG-11439): Display eligible systems alert only when eligible systems filtered

src/SmartComponents/CompletedTaskDetails/JobResultsDetails/EntryDetails.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/EntryRow.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/EntryRowLabel.js, src/SmartComponents/CompletedTaskDetails/JobResultsDetails/ExpandedIssues.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
=> fix(RHINENG-1485): Move status label from expandable section to issue title

src/SmartComponents/CompletedTaskDetails/Columns.js, src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js, src/SmartComponents/CompletedTaskDetails/Filters.js, src/SmartComponents/CompletedTaskDetails/__tests__/CompletedTaskDetails.tests.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
- makes the change for all task jobs, not just conversion task jobs
Before PR (job status says 'Success'):
After PR (job status says 'Completed'):
=> fix(RHINENG-12517): Change 'Success' job status to 'Completed' for all jobs

src/SmartComponents/RunTaskModal/ConversionTaskInputParameters.js
Fixes https://issues.redhat.com/browse/RHINENG-12622.
This makes CONVERT2RHEL_TAINTED_KERNEL_MODULE_CHECK_SKIP and OPTIONAL_REPOSITORIES parameters render optionally for the conversion-to-rhel*-like tasks. This aims to avoid errors when backend hasn't yet updated the tasks with new parameters.
1. Run the PR against stage
2. Go to available tasks, select Pre-conversion analysis for converting to RHEL or Convert to RHEL from CentOS Linux 7 tasks
3. Select eligible system and click Next
4. The modal should stay and no error should happen at this step
=> fix(RHINENG-12622): Optionally render conversion parameters

src/SmartComponents/SystemTable/SelectCustomFilter.js, src/SmartComponents/SystemTable/SystemTable.js, src/SmartComponents/SystemTable/__tests__/SelectCustomFilter.tests.js, src/SmartComponents/SystemTable/constants.js, src/SmartComponents/SystemTable/helpers.js
This PR updates the system eligibility filter in the select systems modal for a task from radio buttons to a single select dropdown. The functionality should remain the same.
Go to the Available tab on the Tasks app and click the Select systems button on a task to load the system modal and select the eligibility filter.
=> fix(RHINENG-13682): Update eligible filter to single select

src/SmartComponents/SystemTable/SelectCustomFilter.js, src/SmartComponents/SystemTable/SystemTable.js, src/SmartComponents/SystemTable/__tests__/SelectCustomFilter.tests.js, src/SmartComponents/SystemTable/__tests__/helpers.test.js, src/SmartComponents/SystemTable/helpers.js
To test:
- Go to the Available tab
- Click Select systems on a task
- Use the eligibility filter
Test by removing the Eligible systems chip. It should remove the chip and apply All systems filter with no chip. Before, we swapped between the All systems and Eligible systems chips.
=> fix(RHINENG-13682): Update to remove All systems chip

src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap, src/SmartComponents/completedTaskDetailsHelpers.js
If the job has a failure message, then display that, rather than the generic message that provides no information as to why the job failed.
=> fix(RHINENG-14254): If a job has a failure message then display it

src/PresentationalComponents/SplitMessages/SplitMessages.js, src/SmartComponents/CompletedTaskDetails/Columns.js, src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap, src/constants.js
I was going to use the Patternfly Truncate component, but I didn't like the expanded text being displayed in a popover.  I couldn't find another Patternfly component that did text truncation with 'Show more / Show less' links, so I used my own.  If there is a Patternfly component that does something similar, then please let me know and I will consider using it instead of the one in this PR.
Screenshot showing 'Show more':
Screenshot showing 'Show less':
=> Truncate long job message text with Show more / Show less links

package-lock.json, package.json, src/SmartComponents/SystemTable/SystemTable.js, src/SmartComponents/SystemTable/__tests__/constants.test.js, src/SmartComponents/SystemTable/constants.js, src/__tests__/helpers.test.js, src/helpers.js
Adds a RHEL AI column to the task systems table, but only when the rhel-ai-update task is chosen.  When testing locally, proxy requests to prod, because stage doesn't have any RHEL AI systems registered.
=> feat(RHINENG-17466): Add RHEL AI column to task systems table

src/SmartComponents/ActivityTable/Columns.js, src/SmartComponents/ActivityTable/__tests__/__snapshots__/ActivityTable.tests.js.snap
Tasks activities table first column contains links which are clickable when loading yielding 404 error.  This PR removes the link whilst the table is loading:
Before fix if you click on any of the Task entries whilst the table is loading you'll get a 404 error:
After fix you can't click on any of the Tasks entries whilst the table is loading:
=> fix(RHINENG-17743): Remove link from ActivityTable when table is loading

src/helpers.js
No need to put Lightspeed/Insights in the connection tooltip.  Just 'Red Hat' is enough because rhc status checks more than just the connection to Red Hat Lightspeed/Insights.  Plus the useFeatureFlag command was failing anyway :open_mouth:
=> fix(RHINENG-19596): Remove brand name from connected column
