RedHatInsights/tasks-frontend

.dependabot/config.yml
src/Routes.js

Also updated `webpackChunkName` of `TasksPage`.

Update dependabot config

---

api.js
package-lock.json
package.json
src/PresentationalComponents/AvailableTasksTable/AvailableTasksTable.js
src/PresentationalComponents/CompletedTasksTable/Columns.js
src/PresentationalComponents/CompletedTasksTable/CompletedTasksTable.js
src/PresentationalComponents/CompletedTasksTable/__tests__/CompletedTasksTable.tests.js
src/PresentationalComponents/CompletedTasksTable/__tests__/__snapshots__/CompletedTasksTable.tests.js.snap
src/SmartComponents/CompletedTasks/CompletedTasks.js
src/SmartComponents/TasksPage/TasksPage.js
src/Utilities/hooks/useTableTools/Components/TasksTables.js
src/Utilities/hooks/useTableTools/Components/__tests__/TasksTable.fixtures.js
src/Utilities/hooks/useTableTools/Components/__tests__/TasksTables.tests.js
src/Utilities/hooks/useTableTools/Components/__tests__/__snapshots__/TasksTables.tests.js.snap
src/Utilities/hooks/useTableTools/__tests__/__fixtures__/columns.fixtures.js
src/Utilities/hooks/useTableTools/__tests__/__fixtures__/items.fixtures.js
src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useRowsBuilder.tests.js.snap
src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useTableTools.tests.js.snap
src/Utilities/hooks/useTableTools/__tests__/useRowsBuilder.tests.js
src/Utilities/hooks/useTableTools/__tests__/useTableTools.tests.js
src/Utilities/hooks/useTableTools/useRowsBuilder.js
src/Utilities/hooks/useTableTools/useTableTools.js
src/constants.js

Table built but currently contains dummy data.

[RHIF-35] Add completed tasks table

---

src/App.scss
src/PresentationalComponents/TasksPopover/TasksPopover.js
src/SmartComponents/TasksPage/TasksPage.js
src/SmartComponents/TasksPage/__tests__/__snapshots__/TasksPage.tests.js.snap
src/Utilities/hooks/useTableTools/Components/FlexibleFlex.js
src/constants.js

This PR creates the popover for the icon next to the page header for the Tasks app.

[ADVISOR-2508] Create Tasks popover

---

api.js
src/PresentationalComponents/ExecuteTaskButton/ExecuteTaskButton.js
src/PresentationalComponents/ExecuteTaskButton/__tests__/ExecuteTaskButton.tests.js
src/PresentationalComponents/ExecuteTaskButton/__tests__/__snapshots__/ExecuteTaskButton.tests.js.snap
src/SmartComponents/RunTaskModal/RunTaskModal.js
src/SmartComponents/SystemTable/SystemTable.js
src/constants.js
src/store/index.js

This PR allows a user to execute an available task on selected systems.
This functionality will only work on a host that is turned on and actively connected. I'm not sure how to do this locally, but it can be done. Let me know if you test this and we can get a system actively connected and hard-code the id into the code to test it.
A successfully executed task should show a notification with a link to the task. An error should result in a notification noting the error.

[ADVISOR-2584] Execute an available task

---

api.js
src/SmartComponents/CompletedTasksTable/CompletedTasksTable.js
src/SmartComponents/CompletedTasksTable/__tests__/CompletedTasksTable.tests.js
src/SmartComponents/CompletedTasksTable/__tests__/__snapshots__/CompletedTasksTable.tests.js.snap
src/SmartComponents/TasksPage/__tests__/TasksPage.tests.js
src/Utilities/hooks/useTableTools/Components/TasksTables.js
src/Utilities/hooks/useTableTools/Components/__tests__/TasksTable.fixtures.js
src/Utilities/hooks/useTableTools/Components/__tests__/TasksTables.tests.js
src/Utilities/hooks/useTableTools/Components/__tests__/__snapshots__/TasksTables.tests.js.snap

Pagination fixed for completed tasks table

[ADVISOR-2597] Fix completed tasks table pagination

---

api.js
src/SmartComponents/SystemTable/SystemTable.js
src/SmartComponents/SystemTable/constants.js
src/SmartComponents/SystemTable/helpers.js

Tags filtering will be added when supported by the backend.

[ADVISOR-2642] Add filter and sorting to systems table

---

scripts/release-prod-beta
scripts/release-prod-stable
scripts/release-stage-stable

Add scripts for release to stage-stable, prod-beta and prod-stable.

Add release scripts

---

src/SmartComponents/CompletedTaskDetails/Columns.js
src/SmartComponents/CompletedTaskDetails/__tests__/CompletedTaskDetails.tests.js
src/SmartComponents/CompletedTaskDetails/__tests__/__fixtures__/completedTasksDetails.fixtures.js
src/SmartComponents/completedTaskDetailsHelpers.js
src/Utilities/helpers.js
src/constants.js

When a task is "Running" the "End time" and "Systems with messages" fields of the CompletedTaskDetails page will show a `-` in place of other info. In addition, the "Messages" column in the jobs table will display as "No result yet" until `results.message` returns a value.

[ADVISOR-2557] Create an in-progress task

---

src/SmartComponents/CompletedTasksTable/CompletedTasksTable.js
src/SmartComponents/CompletedTasksTable/__tests__/CompletedTasksTable.tests.js
src/SmartComponents/CompletedTasksTable/__tests__/__snapshots__/CompletedTasksTable.tests.js.snap
src/constants.js

This PR fixes default sort on the completed tasks table. Now default sort is "Run date/time" DESC.

Fix last minute issues

---

src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js

To repro:
Open a task
Click "Run task again"
Click "View progress" on notification alert
The url will update, but you will not be renavigated. This PR reloads this component on param change from url.

[ADVISOR-2867] Redirect when rerunning task from details

---

src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js
src/SmartComponents/CompletedTaskDetails/JobResultsDetails/EntryDetails.js
src/SmartComponents/CompletedTaskDetails/__tests__/CompletedTaskDetails.tests.js
src/SmartComponents/CompletedTaskDetails/__tests__/__fixtures__/completedTasksDetails.fixtures.js
src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
src/SmartComponents/completedTaskDetailsHelpers.js
src/Utilities/helpers.js
src/Utilities/hooks/useTableTools/useExpandable.js

Before, if a task completed successfully and had a report, but alert: false, the details wouldn't render properly and the expandable row wasn't present. This PR fixes that.
This PR also fixes a sort issue on the Activity table "Systems" row.
This PR also fixes a bug to render the icon in the labels for task details.

Fix expandable bug

---

src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js
src/SmartComponents/CompletedTaskDetails/__tests__/CompletedTaskDetails.tests.js
src/SmartComponents/CompletedTaskDetails/__tests__/__fixtures__/completedTasksDetails.fixtures.js
src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
src/Utilities/hooks/useTableTools/useExpandable.js
src/Utilities/hooks/useTableTools/useRowsBuilder.js

To repro:
- Find a completed task with multiple expandable rows
- Open one expandable row
You will see that all other expandable rows open as well. This PR fixes that.
Also added the description to the completed task page.
Added tests.

[ADVISOR-2871] Fix jobs with multiple expandable rows

---

src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js
src/SmartComponents/CompletedTaskDetails/Filters.js
src/SmartComponents/CompletedTaskDetails/__tests__/CompletedTaskDetails.tests.js
src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap

Open the completed task details page and the Status filter is set as the default. This PR sets System filter as the default.

[ADVISOR-2886] System filter should be default

---

src/SmartComponents/CompletedTaskDetails/Columns.js
src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
src/SmartComponents/SystemTable/constants.js
src/helpers.js

The system links for jobs on a completed task were not properly linked to open in a new tab. This is now fixed and I consolidated the code to create a system link.

[ADVISOR-2882] Update additional system links

---

src/SmartComponents/CompletedTaskDetails/Columns.js
src/SmartComponents/SystemTable/SystemTable.js
src/SmartComponents/SystemTable/constants.js
src/helpers.js

Relates to https://issues.redhat.com/browse/RHIF-130.
This should fix the hooks order error happening in stage-beta (see jira/screenshot).

refactor(RHIF-130): Move useChrome to components

---

config/setupTests.js
src/SmartComponents/AvailableTasks/AvailableTasks.js
src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js
src/SmartComponents/CompletedTaskDetails/__tests__/CompletedTaskDetails.tests.js

To test, navigate to all pages of tasks and verify that the title changes appropriately.

fix(RHIF-267): adopt useChrome updateDocumentTitle hook

---

src/Routes.js

Ticket: [RHIF-200](https://issues.redhat.com/browse/RHIF-200)
[Dashboard PR](https://github.com/RedHatInsights/insights-dashboard/pull/375)

[RHIF-200] Add Empty State

---

src/Routes.js

There was a misunderstanding, the original functionality was correct
[Previous PR](https://github.com/RedHatInsights/tasks-frontend/pull/94)

fix(RHIF-200): Don't show empty state by default

---

package-lock.json
package.json
src/SmartComponents/ActivityTable/ActivityTable.js
src/SmartComponents/ActivityTable/__tests__/ActivityTable.tests.js
src/SmartComponents/ActivityTable/__tests__/__snapshots__/ActivityTable.tests.js.snap
src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
src/Utilities/hooks/usePromiseQueue.js
src/Utilities/hooks/useTableTools/Components/__tests__/__snapshots__/TasksTables.tests.js.snap
src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useTableSort.test.js.snap
src/Utilities/hooks/useTableTools/__tests__/__snapshots__/useTableTools.tests.js.snap
src/Utilities/hooks/useTableTools/useFilterConfig.js
src/Utilities/hooks/useTableTools/useTableSort.js
src/constants.js

This fix simple batch fetches Activity Table data to allow sorting, filtering and pagination to work correctly. Currently in stage, we are only fetching 500 tasks because fetching 1000 tasks is too much on the api. So now we fetch in batches to allow all items to be fetched.

fix(RHINENG-969): properly paginated/sort/filter Activity table

---

src/SmartComponents/AvailableTasks/AvailableTasksTable.js

Updated the check to show pre-conversion tasks in all preview environments.

Show pre-conversion tasks in stage-beta and prod-beta

---

src/SmartComponents/warningConstants.js

Follows up on https://github.com/RedHatInsights/tasks-frontend/pull/108
Nothing urgent, just making sure upgrades task take advantage of new feature as well :)

Add backup warning for leapp upgrade task

---

src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
src/SmartComponents/completedTaskDetailsHelpers.js

Steps to Reproduce
1. Go to /insights/tasks/executed/5938 on insights-qa account See the message and that there is no expandable row button
2. This PR shows the expandable content.

bug(RHINENG-3371): Expandable row content not showing

---

src/SmartComponents/CompletedTaskDetails/TaskEntries.js

Test this on insights-qa account on /tasks/executed/6009. It will fail in stage but pass on this PR.

Add severity mapping for conversion tasks

---

README.md
package.json

@johnsonm325 I was just trying to setup the project today and noticed these couple of things in the README.  Hopefully these changes are correct.

Add patch:hosts command and update README

---

src/constants.js

@johnsonm325 another easy one I noticed when I was trying to configure the service.  The links in the Tasks popover weren't very specific and both pointed to the same location (the URL had changed and re-directs were put in place but redirected to the same document).  Hopefully this is ok too.
I'm not able to add reviewers, that's why I'm @ you in the MR body :(

Update the RH document links in the Tasks popover

---

config/prod.webpack.config.js

This fixes broken stage preview env by properly checking preview/stable env variable.

chore(prodWebpackConfig): add proper beta/stable code check

---

src/SmartComponents/CompletedTaskDetails/JobResultsDetails/ExpandedIssues.js
src/SmartComponents/CompletedTaskDetails/JobResultsDetails/JobResultsDetails.js

Before patch to ExpandedIssues:
After patch to ExpandedIssues:

Gracefully handle unexpected task output

---

src/App.scss
src/PresentationalComponents/TasksPopover/TasksPageHeaderPopover.js
src/PresentationalComponents/TasksPopover/TasksPopover.js
src/SmartComponents/TasksPage/__tests__/__snapshots__/TasksPage.tests.js.snap
src/constants.js

Go to tasks app. In the page header, you'll see the Question mark circle icon. Click it to see the popover and notice the formatting.
Check Image Builder for same type of popover with different filtering. This PR matches the formatting there as requested by QE.
Check Jira card for additional details.

bug(RHINENG-3777): Fix tasks popover formatting

---

src/SmartComponents/ActivityTable/ActivityTable.js
src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js
src/SmartComponents/RefreshFooterContent.js

Fixes https://issues.redhat.com/browse/RHINENG-3652.
This adds missing timezone indication to the "last updated" timestamp on the task page. I am using a component from PatternFly that allows to build the string with the timezone automatically.
- Test the PR with any task which has the "running" status, and verify that you can see the timestamp using and including your timezone.
- Test any "finished" tasks and verify that there are no changes to the "all jobs completed" text.

fix(RHINENG-3652): Show timezone for last updated date label

---

src/SmartComponents/AvailableTasks/TaskCard.js
src/SmartComponents/RunTaskModal/SystemsSelect.js
src/SmartComponents/RunTaskModal/__tests__/RunTaskModalBody.tests.js

This refactors the layout for task modals, adds missing icons, and also adds a quickstart button for the tasks that have a quickstart associated with it.

chore: Minor improvements to the task modals

---

src/SmartComponents/CompletedTaskDetails/Columns.js
src/SmartComponents/CompletedTaskDetails/__tests__/__snapshots__/CompletedTaskDetails.tests.js.snap
src/SmartComponents/completedTaskDetailsHelpers.js

Before PR, the alert count value was incorrect:
After PR, alert count value is correct and successful job isn't flagged with Alert:

fix(RHINENG-7758): Correct alert_count and flagging jobs with Alert

---

src/SmartComponents/ActivityTable/Filters.js
src/SmartComponents/CompletedTaskDetails/Columns.js
src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.js
src/SmartComponents/CompletedTaskDetails/CompletedTaskDetails.scss
src/SmartComponents/CompletedTaskDetails/Filters.js
src/SmartComponents/CompletedTaskDetails/JobResultsDetails/EntryDetails.js
src/SmartComponents/completedTaskDetailsHelpers.js
src/Utilities/helpers.js

- fix column width inconsistencies
- add status column & filter for conversion tasks
- fix end date NaN

fix(RHINENG-8939): Various fixes for tasks detail table/page

---

src/SmartComponents/ActivityTable/Columns.js
src/SmartComponents/ActivityTable/__tests__/__snapshots__/ActivityTable.tests.js.snap

After this PR was merged https://github.com/RedHatInsights/tasks-frontend/pull/168, I noticed that the Status column in the Activity table was no longer showing loading rows. So I fixed the issue and did a slight refactor to some bits of the code.

fix: Status column shows loading cell

---

package-lock.json
src/SmartComponents/ActivityTable/__tests__/ActivityTable.tests.js
src/SmartComponents/AvailableTasks/QuickstartButton.js
src/SmartComponents/AvailableTasks/TaskCard.js
src/SmartComponents/RunTaskModal/RunTaskModal.js
src/SmartComponents/RunTaskModal/TaskDescription.js
src/SmartComponents/RunTaskModal/__tests__/TaskDescription.test.js

Fixes https://issues.redhat.com/browse/RHINENG-9613, https://issues.redhat.com/browse/RHINENG-9614.
Tasks Modal - check Tasks Modal from Available tab, Activity table kebab, and from the Run task again button on Task Detail page
- Ensure all links in all 3 tasks (upgrade, conversion, & pre-conversion) descriptions open in new tabs
- Remove the icon from the "Help me get started" button
- Make both buttons ("Download preview of playbook" and "Help me get started") PF "Link button" styling
Tasks - check expandable task card on the Available tab
- Ensure all links in the three task (upgrade, conversion, & pre-conversion) descriptions open in new tabs
- Make the "Help me get started" button styled as "secondary" and remove the arrow icon

fix(RHINENG-9613 & RHINENG-9614): Update task details UI

---

deploy/testing-integration.yml

Name update from hms-integration to insights-experiences.

fix(HMS-3962): Update Integration test image for IQE

---

src/SmartComponents/SystemTable/__tests__/helpers.test.js
src/SmartComponents/SystemTable/helpers.js

This fixes issues converting the OS group filter value to the Tasks API operating_system filter. 
How to test:
1) Open any page with systems and test filtering them (not only the OS filter)

fix(SystemsTable): RHINENG-10561 - Fix OS filter conversion

---

package-lock.json

https://issues.redhat.com/browse/RHINENG-3439

Update `decode-uri-component` to fix a CVE

---

package-lock.json

https://issues.redhat.com/browse/RHINENG-8445

chore(deps): Update sanitize-html to fix a CVE

---

src/PresentationalComponents/DeleteCancelTaskModal/DeleteCancelTaskModal.js
src/SmartComponents/RunTaskModal/RunTaskModal.js
src/SmartComponents/RunTaskModal/hooks/useBulkSystemSelect.js
src/SmartComponents/SystemTable/SystemTable.js
src/SmartComponents/SystemTable/__tests__/SystemTable.tests.js
src/SmartComponents/SystemTable/__tests__/__fixtures__/SystemTable.fixtures.js
src/SmartComponents/SystemTable/constants.js
src/SmartComponents/SystemTable/hooks.js
src/helpers.js

feat(RHINENG-10818): Add connected status column to SystemTable

---

src/SmartComponents/RunTaskModal/__tests__/RunTaskModal.tests.js
src/SmartComponents/RunTaskModal/hooks/useModalActions.js

Fixes https://issues.redhat.com/browse/RHINENG-8807.
This is a quick request to update aria-label's for better Pendo tracking.

fix(RHINENG-8807): Improve aria-label's for Next buttons

---

src/SmartComponents/RunTaskModal/ConversionTaskInputParameters.js
src/SmartComponents/RunTaskModal/InputParameters.js
src/SmartComponents/RunTaskModal/ParameterCheckbox.js
src/SmartComponents/RunTaskModal/ParameterCheckboxGroup.js
src/SmartComponents/RunTaskModal/ParameterDropdown.js
src/SmartComponents/RunTaskModal/ParameterTextbox.js
src/SmartComponents/RunTaskModal/__tests__/InputParameters.tests.js
src/Utilities/helpers.js

- Add dropdown and textbox input elements for handling those types of parameters

feat(RHINENG-10663): Handle different types of form elements for InputParameters

---

src/SmartComponents/RunTaskModal/ConversionTaskInputParameters.js
src/constants.js

- Add CONVERT2RHEL_TAINTED_KERNEL_MODULE_CHECK_SKIP
- Update the descriptions for a few parameters
Screenshot showing updates:

fix(RHINENG-11967): Update conversion parameters

---

src/SmartComponents/ActivityTable/Columns.js
src/Utilities/hooks/useTableTools/Components/__tests__/__snapshots__/TasksTables.tests.js.snap

fix(RHINENG-1478): Update Task status text styling

---

src/SmartComponents/CompletedTaskDetails/ParameterDetails.js
src/SmartComponents/CompletedTaskDetails/ParameterDetails.scss

fix(RHINENG-12480): Put task parameter details in expandable section

---

src/SmartComponents/SystemTable/NoCentOsEmptyState.js

https://issues.redhat.com/browse/RHINENG-14952

fix(CentOS empty state): Update broken link to docs

---

build_deploy.sh
package-lock.json
package.json

https://issues.redhat.com/browse/RHINENG-15358
- use node v18 in pipelines
- remove unused and outdated babel packages

chore(RHINENG-15358): Cleanup and consolidate frontend repositories

---

.gitmodules
.tekton/tasks-frontend-pull-request.yaml
.tekton/tasks-frontend-push.yaml

[RHINENG-16169](https://issues.redhat.com/browse/RHINENG-16169)

chore(build): use shared Dockerfile

---

src/SmartComponents/completedTaskDetailsHelpers.js

Forgot to add this in my last PR, so doing it in this one!

fix(RHINENG-14254): Display failed job details, if any

---

src/PresentationalComponents/TasksPopover/TasksPageHeaderPopover.js
src/SmartComponents/TasksPage/__tests__/__snapshots__/TasksPage.tests.js.snap
src/constants.js

Spacing was inconsistent with other apps.

fix: Fix header tooltip icon spacing
